Repository HelpingHandsProject/Application, pull requests merged in 2020-03, with the labels that each got.

#24 Edited the README.md of the dev branch
  README.md
  app_design_v0.1.jpg
Labels: documentation

#35 Feature/authentification and restructuring
  .gitignore
  android/app/build.gradle
  android/build.gradle
  lib/Constants/colors.dart
  lib/Elements/baseAppBar.dart
  lib/Elements/formFields.dart
  lib/Elements/logoutAppBar.dart
  lib/main.dart
  lib/screens/authenticate/authenticate.dart
  lib/screens/authenticate/register.dart
  lib/screens/authenticate/sign_in.dart
  lib/screens/authenticate/verify_email.dart
  lib/screens/home/home.dart
  lib/screens/wrapper.dart
  lib/services/auth.dart
  lib/services/crud.dart
  lib/shared/loading.dart
  lib/widgets/ParametrizedAppBar.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#43 Feature/fix color variable's naming
  android/app/google-services.json
  lib/Constants/colors.dart
  lib/Elements/baseAppBar.dart
  lib/screens/authenticate/register.dart
  lib/screens/authenticate/sign_in.dart
  lib/screens/authenticate/verify_email.dart
  lib/screens/home/home.dart
  lib/shared/loading.dart
Labels: enhancement

#45 Fixed wrong return type to void
  lib/Elements/logoutAppBar.dart
Labels: refactor

#46 Feature/fix immutable class contains mutable property
  lib/screens/authenticate/verify_email.dart
  lib/screens/home/home.dart
Labels: refactor

#49 Feature/Models for data representation and conversion
  lib/Constants/magic_strings.dart
  lib/models/chat.dart
  lib/models/chatMessage.dart
  lib/models/rating.dart
  lib/models/request.dart
  lib/models/user.dart
Labels: enhancement

#51 Feature/implement crud for database models
  .gitignore
  lib/Constants/magic_strings.dart
  lib/Elements/formFields.dart
  lib/main.dart
  lib/models/baseModel.dart
  lib/models/chat.dart
  lib/models/chatMessage.dart
  lib/models/request.dart
  lib/models/user.dart
  lib/screens/authenticate/createProfile.dart
  lib/screens/authenticate/register.dart
  lib/screens/wrapper.dart
  lib/services/auth.dart
  lib/services/crud.dart
  lib/utils/list.dart
  lib/utils/query.dart
  lib/utils/type.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#54 Fixed several imports
  lib/Elements/baseRequestContent.dart
  lib/Elements/feedRequestCard.dart
  lib/screens/home/addRequest.dart
  lib/screens/home/home.dart
Labels: refactor

#59 Feature/move logout to settings page
  lib/Elements/baseAppBar.dart
  lib/Elements/clickableIconAppBar.dart
  lib/Elements/logoutAppBar.dart
  lib/screens/authenticate/register.dart
  lib/screens/authenticate/sign_in.dart
  lib/screens/home/addRequest.dart
  lib/screens/home/feed.dart
  lib/screens/home/myRequests.dart
  lib/services/crud.dart
Labels: refactor

#60 Feature/refactor folder names to lower case
  lib/Elements/clickableIconAppBar.dart
  lib/constants/colors.dart
  lib/constants/icons.dart
  lib/constants/magic_strings.dart
  lib/elements/baseAppBar.dart
  lib/elements/baseRequestContent.dart
  lib/elements/feedRequestCard.dart
  lib/elements/formFields.dart
  lib/elements/logoutAppBar.dart
  lib/elements/myRequestCard.dart
  lib/screens/authenticate/createProfile.dart
  lib/screens/authenticate/register.dart
  lib/screens/authenticate/sign_in.dart
  lib/screens/authenticate/verify_email.dart
  lib/screens/home/addRequest.dart
  lib/screens/home/feed.dart
  lib/screens/home/home.dart
  lib/screens/home/myRequests.dart
  lib/screens/home/profileSettings.dart
  lib/shared/loading.dart
  lib/widgets/ParametrizedAppBar.dart
Labels: refactor
